const _ = require('lodash')

let i = 0

const generateUUID = (prefix = '00000000') => () => {
  const suffix = `${++i}`.padStart(12, '0')
  return `${prefix}-0000-0000-0000-${suffix}`
}
const uuid = generateUUID('50000000')

module.exports = async function (knex, ctx) {
  // 建立資料
  const courses = [
    // {
    //   id: uuid(),
    //   created_at: new Date(),
    //   name: '英文',
    //   english_name: 'English',
    //   slug: '2020f1aEng',
    //   unit: 2,
    //   school_dashboard_id: ctx.schoolsDashboards.obj['2019/2020 Dashboard'].id,
    //   school_id: ctx.schools.obj['school-cdsj1'].id,
    //   cls_id: ctx.classes.obj['19-f1a.id'],
    //   type: 'required',
    //   term: 0
    // },
    // {
    //   id: uuid(),
    //   created_at: new Date(),
    //   name: '英文',
    //   english_name: 'English',
    //   slug: '2020f1bEng',
    //   unit: 2,
    //   school_dashboard_id: ctx.schoolsDashboards.obj['2019/2020 Dashboard'].id,
    //   school_id: ctx.schools.obj['school-cdsj1'].id,
    //   cls_id: ctx.classes.obj['19-f1b.id'],
    //   type: 'required',
    //   term: 0
    // },
    // {
    //   id: uuid(),
    //   created_at: new Date(),
    //   name: '英文',
    //   english_name: 'English',
    //   slug: '2020f1cEng',
    //   unit: 2,
    //   school_dashboard_id: ctx.schoolsDashboards.obj['2019/2020 Dashboard'].id,
    //   school_id: ctx.schools.obj['school-cdsj1'].id,
    //   cls_id: ctx.classes.obj['19-f1c.id'],
    //   type: 'required',
    //   term: 0
    // },
    // {
    //   id: uuid(),
    //   created_at: new Date(),
    //   name: '英文',
    //   english_name: 'English',
    //   slug: '2020f1dEng',
    //   unit: 2,
    //   school_dashboard_id: ctx.schoolsDashboards.obj['2019/2020 Dashboard'].id,
    //   school_id: ctx.schools.obj['school-cdsj1'].id,
    //   cls_id: ctx.classes.obj['19-f1d.id'],
    //   type: 'required',
    //   term: 0
    // },
    // {
    //   id: uuid(),
    //   created_at: new Date(),
    //   name: '數學',
    //   english_name: 'Math',
    //   slug: '2020f1aMath',
    //   unit: 2,
    //   school_dashboard_id: ctx.schoolsDashboards.obj['2019/2020 Dashboard'].id,
    //   school_id: ctx.schools.obj['school-cdsj1'].id,
    //   cls_id: ctx.classes.obj['19-f1a.id'],
    //   type: 'required',
    //   term: 0
    // },
    // {
    //   id: uuid(),
    //   created_at: new Date(),
    //   name: '數學',
    //   english_name: 'Math',
    //   slug: '2020f1bMath',
    //   unit: 2,
    //   school_dashboard_id: ctx.schoolsDashboards.obj['2019/2020 Dashboard'].id,
    //   school_id: ctx.schools.obj['school-cdsj1'].id,
    //   cls_id: ctx.classes.obj['19-f1b.id'],
    //   type: 'required',
    //   term: 0
    // },
    // {
    //   id: uuid(),
    //   created_at: new Date(),
    //   name: '數學',
    //   english_name: 'Math',
    //   slug: '2020f1cMath',
    //   unit: 2,
    //   school_dashboard_id: ctx.schoolsDashboards.obj['2019/2020 Dashboard'].id,
    //   school_id: ctx.schools.obj['school-cdsj1'].id,
    //   cls_id: ctx.classes.obj['19-f1c.id'],
    //   type: 'required',
    //   term: 0
    // },
    // {
    //   id: uuid(),
    //   created_at: new Date(),
    //   name: '數學',
    //   english_name: 'Math',
    //   slug: '2020f1dMath',
    //   unit: 2,
    //   school_dashboard_id: ctx.schoolsDashboards.obj['2019/2020 Dashboard'].id,
    //   school_id: ctx.schools.obj['school-cdsj1'].id,
    //   cls_id: ctx.classes.obj['19-f1d.id'],
    //   type: 'required',
    //   term: 0
    // },
    // {
    //   id: uuid(),
    //   created_at: new Date(),
    //   name: '程式設計',
    //   english_name: 'Program Design',
    //   slug: '2020electiveProgramDesign',
    //   unit: 1,
    //   school_dashboard_id: ctx.schoolsDashboards.obj['2019/2020 Dashboard'].id,
    //   school_id: ctx.schools.obj['school-cdsj1'].id,
    //   cls_id: '',
    //   type: 'elective',
    //   term: 1
    // },
    // {
    //   id: uuid(),
    //   created_at: new Date(),
    //   name: '資訊安全',
    //   english_name: 'Information Security',
    //   slug: '2020electiveInfoSecurity',
    //   unit: 1,
    //   school_dashboard_id: ctx.schoolsDashboards.obj['2019/2020 Dashboard'].id,
    //   school_id: ctx.schools.obj['school-cdsj1'].id,
    //   cls_id: '',
    //   type: 'elective',
    //   term: 2
    // },
    {
      id: uuid(),
      created_at: new Date(),
      name: '少林足球社',
      english_name: 'Soccer Club',
      slug: '2020clubSoccer',
      credits: 0,
      school_dashboard_id: ctx.schoolsDashboards.obj['cdsj1 2019/2020 Dashboard'].id,
      school_id: ctx.schools.obj['school-cdsj1'].id,
      type: 'activity',
      term: 1
    },
    {
      id: uuid(),
      created_at: new Date(),
      name: '舞蹈社',
      english_name: 'Dance Club',
      slug: '2020clubDance',
      credits: 0,
      school_dashboard_id: ctx.schoolsDashboards.obj['cdsj6 2019/2020 Dashboard'].id,
      school_id: ctx.schools.obj['school-cdsj1'].id,
      type: 'activity',
      term: 1
    }
  ]

  const coursesData = [
    { name: '世史', cls_id: ctx.classes.obj['19-s3aa'].id, slug: 'rewohi1920s3aa' },
    { name: '世史', cls_id: ctx.classes.obj['19-s3ab'].id, slug: 'rewohi1920s3ab' },
    { name: '世史', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'rewohi1920s2aa' },
    { name: '世史', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'rewohi1920s2ab' },
    { name: '世史', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'rewohi1920s1aa' },
    { name: '世史', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'rewohi1920s1ab' },
    { name: '中史', cls_id: ctx.classes.obj['19-s3ab'].id, slug: 'rechhi1920s3ab' },
    { name: '中史', cls_id: ctx.classes.obj['19-s3aa'].id, slug: 'rechhi1920s3aa' },
    { name: '中史', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'rechhi1920s2aa' },
    { name: '中史', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'rechhi1920s2ab' },
    { name: '中史', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'rechhi1920s1aa' },
    { name: '中史', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'rechhi1920s1ab' },
    { name: '中文', cls_id: ctx.classes.obj['19-s3aa'].id, slug: 'rechin1920s3aa' },
    { name: '中文', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'rechin1920s2aa' },
    { name: '中文', cls_id: ctx.classes.obj['19-s3ab'].id, slug: 'rechin1920s3ab' },
    { name: '中文', cls_id: ctx.classes.obj['19-s3sa'].id, slug: 'rechin1920s3sa' },
    { name: '中文', cls_id: ctx.classes.obj['19-s2sa'].id, slug: 'rechin1920s2sa' },
    { name: '中文', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'rechin1920s1aa' },
    { name: '中文', cls_id: ctx.classes.obj['19-s1sa'].id, slug: 'rechin1920s1sa' },
    { name: '中文', cls_id: ctx.classes.obj['19-j1b'].id, slug: 'rechin1920j1b' },
    { name: '中文', cls_id: ctx.classes.obj['19-j2a'].id, slug: 'rechin1920j2a' },
    { name: '中文', cls_id: ctx.classes.obj['19-j1a'].id, slug: 'rechin1920j1a' },
    { name: '中文', cls_id: ctx.classes.obj['19-j1c'].id, slug: 'rechin1920j1c' },
    { name: '中文', cls_id: ctx.classes.obj['19-j2c'].id, slug: 'rechin1920j2c' },
    { name: '中文', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'rechin1920s1ab' },
    { name: '中文', cls_id: ctx.classes.obj['19-j2b'].id, slug: 'rechin1920j2b' },
    { name: '中文', cls_id: ctx.classes.obj['19-j2d'].id, slug: 'rechin1920j2d' },
    { name: '中文', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'rechin1920s2ab' },
    { name: '中文', cls_id: ctx.classes.obj['19-j3a'].id, slug: 'rechin1920j3a' },
    { name: '中文', cls_id: ctx.classes.obj['19-j3c'].id, slug: 'rechin1920j3c' },
    { name: '中文', cls_id: ctx.classes.obj['19-j3b'].id, slug: 'rechin1920j3b' },
    { name: '中文', cls_id: ctx.classes.obj['19-f3a'].id, slug: 'rechin1920f3a' },
    { name: '中文', cls_id: ctx.classes.obj['19-f1a'].id, slug: 'rechin1920f1a' },
    { name: '中文', cls_id: ctx.classes.obj['19-j1d'].id, slug: 'rechin1920j1d' },
    { name: '中文', cls_id: ctx.classes.obj['19-f2a'].id, slug: 'rechin1920f2a' },
    { name: '公民', cls_id: ctx.classes.obj['19-s3aa'].id, slug: 'recied1920s3aa' },
    { name: '公民', cls_id: ctx.classes.obj['19-s3ab'].id, slug: 'recied1920s3ab' },
    { name: '公民', cls_id: ctx.classes.obj['19-s3sa'].id, slug: 'recied1920s3sa' },
    { name: '公民', cls_id: ctx.classes.obj['19-j1a'].id, slug: 'recied1920j1a' },
    { name: '公民', cls_id: ctx.classes.obj['19-j1b'].id, slug: 'recied1920j1b' },
    { name: '公民', cls_id: ctx.classes.obj['19-j1c'].id, slug: 'recied1920j1c' },
    { name: '公民', cls_id: ctx.classes.obj['19-j1d'].id, slug: 'recied1920j1d' },
    { name: '公民', cls_id: ctx.classes.obj['19-f1a'].id, slug: 'recied1920f1a' },
    { name: '公民', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'recied1920s2aa' },
    { name: '公民', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'recied1920s2ab' },
    { name: '公民', cls_id: ctx.classes.obj['19-s2sa'].id, slug: 'recied1920s2sa' },
    { name: '公民', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'recied1920s1aa' },
    { name: '公民', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'recied1920s1ab' },
    { name: '公民', cls_id: ctx.classes.obj['19-s1sa'].id, slug: 'recied1920s1sa' },
    { name: '公民', cls_id: ctx.classes.obj['19-j3a'].id, slug: 'recied1920j3a' },
    { name: '公民', cls_id: ctx.classes.obj['19-j3b'].id, slug: 'recied1920j3b' },
    { name: '公民', cls_id: ctx.classes.obj['19-j2a'].id, slug: 'recied1920j2a' },
    { name: '公民', cls_id: ctx.classes.obj['19-j2b'].id, slug: 'recied1920j2b' },
    { name: '公民', cls_id: ctx.classes.obj['19-j2c'].id, slug: 'recied1920j2c' },
    { name: '公民', cls_id: ctx.classes.obj['19-j2d'].id, slug: 'recied1920j2d' },
    { name: '公民', cls_id: ctx.classes.obj['19-f2a'].id, slug: 'recied1920f2a' },
    { name: '公民', cls_id: ctx.classes.obj['19-j3c'].id, slug: 'recied1920j3c' },
    { name: '公民', cls_id: ctx.classes.obj['19-f3a'].id, slug: 'recied1920f3a' },
    { name: '化學', cls_id: ctx.classes.obj['19-s3sa'].id, slug: 'rechem1920s3sa' },
    { name: '化學', cls_id: ctx.classes.obj['19-s2sa'].id, slug: 'rechem1920s2sa' },
    { name: '化學', cls_id: ctx.classes.obj['19-s1sa'].id, slug: 'rechem1920s1sa' },
    { name: '地理', cls_id: ctx.classes.obj['19-s3aa'].id, slug: 'regeog1920s3aa' },
    { name: '地理', cls_id: ctx.classes.obj['19-s3ab'].id, slug: 'regeog1920s3ab' },
    { name: '地理', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'regeog1920s2aa' },
    { name: '地理', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'regeog1920s2ab' },
    { name: '地理', cls_id: ctx.classes.obj['19-s2sa'].id, slug: 'regeog1920s2sa' },
    { name: '地理', cls_id: ctx.classes.obj['19-j1d'].id, slug: 'regeog1920j1d' },
    { name: '地理', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'regeog1920s1aa' },
    { name: '地理', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'regeog1920s1ab' },
    { name: '地理', cls_id: ctx.classes.obj['19-j3a'].id, slug: 'regeog1920j3a' },
    { name: '地理', cls_id: ctx.classes.obj['19-j3b'].id, slug: 'regeog1920j3b' },
    { name: '地理', cls_id: ctx.classes.obj['19-j3c'].id, slug: 'regeog1920j3c' },
    { name: '地理', cls_id: ctx.classes.obj['19-j2a'].id, slug: 'regeog1920j2a' },
    { name: '地理', cls_id: ctx.classes.obj['19-j2b'].id, slug: 'regeog1920j2b' },
    { name: '地理', cls_id: ctx.classes.obj['19-j2c'].id, slug: 'regeog1920j2c' },
    { name: '地理', cls_id: ctx.classes.obj['19-j2d'].id, slug: 'regeog1920j2d' },
    { name: '地理', cls_id: ctx.classes.obj['19-j1a'].id, slug: 'regeog1920j1a' },
    { name: '地理', cls_id: ctx.classes.obj['19-j1b'].id, slug: 'regeog1920j1b' },
    { name: '地理', cls_id: ctx.classes.obj['19-j1c'].id, slug: 'regeog1920j1c' },
    { name: '地理', cls_id: ctx.classes.obj['19-f3a'].id, slug: 'regeog1920f3a' },
    { name: '地理', cls_id: ctx.classes.obj['19-f2a'].id, slug: 'regeog1920f2a' },
    { name: '地理', cls_id: ctx.classes.obj['19-f1a'].id, slug: 'regeog1920f1a' },
    { name: '宗教', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'rereed1920s1aa' },
    { name: '宗教', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'rereed1920s1ab' },
    { name: '宗教', cls_id: ctx.classes.obj['19-s1sa'].id, slug: 'rereed1920s1sa' },
    { name: '宗教', cls_id: ctx.classes.obj['19-j3a'].id, slug: 'rereed1920j3a' },
    { name: '宗教', cls_id: ctx.classes.obj['19-j3b'].id, slug: 'rereed1920j3b' },
    { name: '宗教', cls_id: ctx.classes.obj['19-j3c'].id, slug: 'rereed1920j3c' },
    { name: '宗教', cls_id: ctx.classes.obj['19-j1a'].id, slug: 'rereed1920j1a' },
    { name: '宗教', cls_id: ctx.classes.obj['19-j1b'].id, slug: 'rereed1920j1b' },
    { name: '宗教', cls_id: ctx.classes.obj['19-j1c'].id, slug: 'rereed1920j1c' },
    { name: '宗教', cls_id: ctx.classes.obj['19-j1d'].id, slug: 'rereed1920j1d' },
    { name: '宗教', cls_id: ctx.classes.obj['19-f2a'].id, slug: 'rereed1920f2a' },
    { name: '宗教', cls_id: ctx.classes.obj['19-f1a'].id, slug: 'rereed1920f1a' },
    { name: '宗教', cls_id: ctx.classes.obj['19-s3aa'].id, slug: 'rereed1920s3aa' },
    { name: '宗教', cls_id: ctx.classes.obj['19-s3ab'].id, slug: 'rereed1920s3ab' },
    { name: '宗教', cls_id: ctx.classes.obj['19-s3sa'].id, slug: 'rereed1920s3sa' },
    { name: '宗教', cls_id: ctx.classes.obj['19-f3a'].id, slug: 'rereed1920f3a' },
    { name: '宗教', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'rereed1920s2aa' },
    { name: '宗教', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'rereed1920s2ab' },
    { name: '宗教', cls_id: ctx.classes.obj['19-s2sa'].id, slug: 'rereed1920s2sa' },
    { name: '宗教', cls_id: ctx.classes.obj['19-j2a'].id, slug: 'rereed1920j2a' },
    { name: '宗教', cls_id: ctx.classes.obj['19-j2b'].id, slug: 'rereed1920j2b' },
    { name: '宗教', cls_id: ctx.classes.obj['19-j2c'].id, slug: 'rereed1920j2c' },
    { name: '宗教', cls_id: ctx.classes.obj['19-j2d'].id, slug: 'rereed1920j2d' },
    { name: '數學', cls_id: ctx.classes.obj['19-s1sa'].id, slug: 'remath1920s1sa' },
    { name: '數學', cls_id: ctx.classes.obj['19-j2d'].id, slug: 'remath1920j2d' },
    { name: '數學', cls_id: ctx.classes.obj['19-f3a'].id, slug: 'remath1920f3a' },
    { name: '數學', cls_id: ctx.classes.obj['19-f2a'].id, slug: 'remath1920f2a' },
    { name: '數學', cls_id: ctx.classes.obj['19-s3ab'].id, slug: 'remath1920s3ab' },
    { name: '數學', cls_id: ctx.classes.obj['19-j2a'].id, slug: 'remath1920j2a' },
    { name: '數學', cls_id: ctx.classes.obj['19-j2b'].id, slug: 'remath1920j2b' },
    { name: '數學', cls_id: ctx.classes.obj['19-s3sa'].id, slug: 'remath1920s3sa' },
    { name: '數學', cls_id: ctx.classes.obj['19-s3aa'].id, slug: 'remath1920s3aa' },
    { name: '數學', cls_id: ctx.classes.obj['19-j2c'].id, slug: 'remath1920j2c' },
    { name: '數學', cls_id: ctx.classes.obj['19-j3a'].id, slug: 'remath1920j3a' },
    { name: '數學', cls_id: ctx.classes.obj['19-j1b'].id, slug: 'remath1920j1b' },
    { name: '數學', cls_id: ctx.classes.obj['19-j1c'].id, slug: 'remath1920j1c' },
    { name: '數學', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'remath1920s2aa' },
    { name: '數學', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'remath1920s2ab' },
    { name: '數學', cls_id: ctx.classes.obj['19-j3b'].id, slug: 'remath1920j3b' },
    { name: '數學', cls_id: ctx.classes.obj['19-j3c'].id, slug: 'remath1920j3c' },
    { name: '數學', cls_id: ctx.classes.obj['19-j1a'].id, slug: 'remath1920j1a' },
    { name: '數學', cls_id: ctx.classes.obj['19-f1a'].id, slug: 'remath1920f1a' },
    { name: '數學', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'remath1920s1aa' },
    { name: '數學', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'remath1920s1ab' },
    { name: '數學', cls_id: ctx.classes.obj['19-j1d'].id, slug: 'remath1920j1d' },
    { name: '數學', cls_id: ctx.classes.obj['19-s2sa'].id, slug: 'remath1920s2sa' },
    { name: '會計', cls_id: ctx.classes.obj['19-s3aa'].id, slug: 'reacco1920s3aa' },
    { name: '會計', cls_id: ctx.classes.obj['19-s3ab'].id, slug: 'reacco1920s3ab' },
    { name: '會計', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'reacco1920s2aa' },
    { name: '會計', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'reacco1920s2ab' },
    { name: '會計', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'reacco1920s1aa' },
    { name: '會計', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'reacco1920s1ab' },
    { name: '歷史', cls_id: ctx.classes.obj['19-j3a'].id, slug: 'rehist1920j3a' },
    { name: '歷史', cls_id: ctx.classes.obj['19-j3b'].id, slug: 'rehist1920j3b' },
    { name: '歷史', cls_id: ctx.classes.obj['19-j3c'].id, slug: 'rehist1920j3c' },
    { name: '歷史', cls_id: ctx.classes.obj['19-j1a'].id, slug: 'rehist1920j1a' },
    { name: '歷史', cls_id: ctx.classes.obj['19-j1b'].id, slug: 'rehist1920j1b' },
    { name: '歷史', cls_id: ctx.classes.obj['19-f2a'].id, slug: 'rehist1920f2a' },
    { name: '歷史', cls_id: ctx.classes.obj['19-f1a'].id, slug: 'rehist1920f1a' },
    { name: '歷史', cls_id: ctx.classes.obj['19-s1sa'].id, slug: 'rehist1920s1sa' },
    { name: '歷史', cls_id: ctx.classes.obj['19-j1c'].id, slug: 'rehist1920j1c' },
    { name: '歷史', cls_id: ctx.classes.obj['19-j1d'].id, slug: 'rehist1920j1d' },
    { name: '歷史', cls_id: ctx.classes.obj['19-j2a'].id, slug: 'rehist1920j2a' },
    { name: '歷史', cls_id: ctx.classes.obj['19-j2b'].id, slug: 'rehist1920j2b' },
    { name: '歷史', cls_id: ctx.classes.obj['19-j2c'].id, slug: 'rehist1920j2c' },
    { name: '歷史', cls_id: ctx.classes.obj['19-j2d'].id, slug: 'rehist1920j2d' },
    { name: '歷史', cls_id: ctx.classes.obj['19-f3a'].id, slug: 'rehist1920f3a' },
    { name: '物理', cls_id: ctx.classes.obj['19-s3sa'].id, slug: 'rephys1920s3sa' },
    { name: '物理', cls_id: ctx.classes.obj['19-s2sa'].id, slug: 'rephys1920s2sa' },
    { name: '物理', cls_id: ctx.classes.obj['19-s1sa'].id, slug: 'rephys1920s1sa' },
    { name: '生物', cls_id: ctx.classes.obj['19-s3sa'].id, slug: 'rebiol1920s3sa' },
    { name: '生物', cls_id: ctx.classes.obj['19-s2sa'].id, slug: 'rebiol1920s2sa' },
    { name: '生物', cls_id: ctx.classes.obj['19-s1sa'].id, slug: 'rebiol1920s1sa' },
    { name: '科學', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'rescie1920s2aa' },
    { name: '科學', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'rescie1920s2ab' },
    { name: '科學', cls_id: ctx.classes.obj['19-f3a'].id, slug: 'rescie1920f3a' },
    { name: '科學', cls_id: ctx.classes.obj['19-f2a'].id, slug: 'rescie1920f2a' },
    { name: '科學', cls_id: ctx.classes.obj['19-f1a'].id, slug: 'rescie1920f1a' },
    { name: '科學', cls_id: ctx.classes.obj['19-j2b'].id, slug: 'rescie1920j2b' },
    { name: '科學', cls_id: ctx.classes.obj['19-j2c'].id, slug: 'rescie1920j2c' },
    { name: '科學', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'rescie1920s1ab' },
    { name: '科學', cls_id: ctx.classes.obj['19-j2a'].id, slug: 'rescie1920j2a' },
    { name: '科學', cls_id: ctx.classes.obj['19-j1a'].id, slug: 'rescie1920j1a' },
    { name: '科學', cls_id: ctx.classes.obj['19-j1d'].id, slug: 'rescie1920j1d' },
    { name: '科學', cls_id: ctx.classes.obj['19-j3b'].id, slug: 'rescie1920j3b' },
    { name: '科學', cls_id: ctx.classes.obj['19-j3c'].id, slug: 'rescie1920j3c' },
    { name: '科學', cls_id: ctx.classes.obj['19-j2d'].id, slug: 'rescie1920j2d' },
    { name: '科學', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'rescie1920s1aa' },
    { name: '科學', cls_id: ctx.classes.obj['19-j3a'].id, slug: 'rescie1920j3a' },
    { name: '科學', cls_id: ctx.classes.obj['19-j1b'].id, slug: 'rescie1920j1b' },
    { name: '科學', cls_id: ctx.classes.obj['19-j1c'].id, slug: 'rescie1920j1c' },
    { name: '美術', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'reviar1920s2aa' },
    { name: '美術', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'reviar1920s2ab' },
    { name: '美術', cls_id: ctx.classes.obj['19-s2sa'].id, slug: 'reviar1920s2sa' },
    { name: '美術', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'reviar1920s1aa' },
    { name: '美術', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'reviar1920s1ab' },
    { name: '美術', cls_id: ctx.classes.obj['19-s1sa'].id, slug: 'reviar1920s1sa' },
    { name: '美術', cls_id: ctx.classes.obj['19-j3a'].id, slug: 'reviar1920j3a' },
    { name: '美術', cls_id: ctx.classes.obj['19-j3b'].id, slug: 'reviar1920j3b' },
    { name: '美術', cls_id: ctx.classes.obj['19-j3c'].id, slug: 'reviar1920j3c' },
    { name: '美術', cls_id: ctx.classes.obj['19-f2a'].id, slug: 'reviar1920f2a' },
    { name: '美術', cls_id: ctx.classes.obj['19-f1a'].id, slug: 'reviar1920f1a' },
    { name: '美術', cls_id: ctx.classes.obj['19-j2a'].id, slug: 'reviar1920j2a' },
    { name: '美術', cls_id: ctx.classes.obj['19-j2b'].id, slug: 'reviar1920j2b' },
    { name: '美術', cls_id: ctx.classes.obj['19-j2c'].id, slug: 'reviar1920j2c' },
    { name: '美術', cls_id: ctx.classes.obj['19-j2d'].id, slug: 'reviar1920j2d' },
    { name: '美術', cls_id: ctx.classes.obj['19-j1a'].id, slug: 'reviar1920j1a' },
    { name: '美術', cls_id: ctx.classes.obj['19-j1b'].id, slug: 'reviar1920j1b' },
    { name: '美術', cls_id: ctx.classes.obj['19-j1c'].id, slug: 'reviar1920j1c' },
    { name: '美術', cls_id: ctx.classes.obj['19-j1d'].id, slug: 'reviar1920j1d' },
    { name: '美術', cls_id: ctx.classes.obj['19-f3a'].id, slug: 'reviar1920f3a' },
    { name: '英文', cls_id: ctx.classes.obj['19-s3aa'].id, slug: 'reengl1920s3aa' },
    { name: '英文', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'reengl1920s2ab' },
    { name: '英文', cls_id: ctx.classes.obj['19-j2a'].id, slug: 'reengl1920j2a' },
    { name: '英文', cls_id: ctx.classes.obj['19-j2b'].id, slug: 'reengl1920j2b' },
    { name: '英文', cls_id: ctx.classes.obj['19-j2c'].id, slug: 'reengl1920j2c' },
    { name: '英文', cls_id: ctx.classes.obj['19-j2d'].id, slug: 'reengl1920j2d' },
    { name: '英文', cls_id: ctx.classes.obj['19-s1sa'].id, slug: 'reengl1920s1sa' },
    { name: '英文', cls_id: ctx.classes.obj['19-j3a'].id, slug: 'reengl1920j3a' },
    { name: '英文', cls_id: ctx.classes.obj['19-j3c'].id, slug: 'reengl1920j3c' },
    { name: '英文', cls_id: ctx.classes.obj['19-j3b'].id, slug: 'reengl1920j3b' },
    { name: '英文', cls_id: ctx.classes.obj['19-j1a'].id, slug: 'reengl1920j1a' },
    { name: '英文', cls_id: ctx.classes.obj['19-j1b'].id, slug: 'reengl1920j1b' },
    { name: '英文', cls_id: ctx.classes.obj['19-j1c'].id, slug: 'reengl1920j1c' },
    { name: '英文', cls_id: ctx.classes.obj['19-j1d'].id, slug: 'reengl1920j1d' },
    { name: '英文', cls_id: ctx.classes.obj['19-f3a'].id, slug: 'reengl1920f3a' },
    { name: '英文', cls_id: ctx.classes.obj['19-f2a'].id, slug: 'reengl1920f2a' },
    { name: '英文', cls_id: ctx.classes.obj['19-f1a'].id, slug: 'reengl1920f1a' },
    { name: '英文', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'reengl1920s1aa' },
    { name: '英文', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'reengl1920s1ab' },
    { name: '英文', cls_id: ctx.classes.obj['19-s3ab'].id, slug: 'reengl1920s3ab' },
    { name: '英文', cls_id: ctx.classes.obj['19-s2sa'].id, slug: 'reengl1920s2sa' },
    { name: '英文', cls_id: ctx.classes.obj['19-s3sa'].id, slug: 'reengl1920s3sa' },
    { name: '英文', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'reengl1920s2aa' },
    { name: '葡文', cls_id: ctx.classes.obj['19-s3aa'].id, slug: 'report1920s3aa' },
    { name: '葡文', cls_id: ctx.classes.obj['19-s3ab'].id, slug: 'report1920s3ab' },
    { name: '葡文', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'report1920s2aa' },
    { name: '葡文', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'report1920s2ab' },
    { name: '葡文', cls_id: ctx.classes.obj['19-j3a'].id, slug: 'report1920j3a' },
    { name: '葡文', cls_id: ctx.classes.obj['19-j3b'].id, slug: 'report1920j3b' },
    { name: '葡文', cls_id: ctx.classes.obj['19-j3c'].id, slug: 'report1920j3c' },
    { name: '葡文', cls_id: ctx.classes.obj['19-f3a'].id, slug: 'report1920f3a' },
    { name: '葡文', cls_id: ctx.classes.obj['19-f2a'].id, slug: 'report1920f2a' },
    { name: '葡文', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'report1920s1aa' },
    { name: '葡文', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'report1920s1ab' },
    { name: '葡文', cls_id: ctx.classes.obj['19-j2a'].id, slug: 'report1920j2a' },
    { name: '葡文', cls_id: ctx.classes.obj['19-j2b'].id, slug: 'report1920j2b' },
    { name: '葡文', cls_id: ctx.classes.obj['19-j2c'].id, slug: 'report1920j2c' },
    { name: '葡文', cls_id: ctx.classes.obj['19-j2d'].id, slug: 'report1920j2d' },
    { name: '葡文', cls_id: ctx.classes.obj['19-j1a'].id, slug: 'report1920j1a' },
    { name: '葡文', cls_id: ctx.classes.obj['19-j1c'].id, slug: 'report1920j1c' },
    { name: '葡文', cls_id: ctx.classes.obj['19-j1d'].id, slug: 'report1920j1d' },
    { name: '葡文', cls_id: ctx.classes.obj['19-j1b'].id, slug: 'report1920j1b' },
    { name: '葡文', cls_id: ctx.classes.obj['19-f1a'].id, slug: 'report1920f1a' },
    { name: '電腦', cls_id: ctx.classes.obj['19-s3aa'].id, slug: 'recosc1920s3aa' },
    { name: '電腦', cls_id: ctx.classes.obj['19-s3ab'].id, slug: 'recosc1920s3ab' },
    { name: '電腦', cls_id: ctx.classes.obj['19-s3sa'].id, slug: 'recosc1920s3sa' },
    { name: '電腦', cls_id: ctx.classes.obj['19-j3a'].id, slug: 'recosc1920j3a' },
    { name: '電腦', cls_id: ctx.classes.obj['19-j3b'].id, slug: 'recosc1920j3b' },
    { name: '電腦', cls_id: ctx.classes.obj['19-j3c'].id, slug: 'recosc1920j3c' },
    { name: '電腦', cls_id: ctx.classes.obj['19-f3a'].id, slug: 'recosc1920f3a' },
    { name: '電腦', cls_id: ctx.classes.obj['19-f2a'].id, slug: 'recosc1920f2a' },
    { name: '電腦', cls_id: ctx.classes.obj['19-f1a'].id, slug: 'recosc1920f1a' },
    { name: '電腦', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'recosc1920s2aa' },
    { name: '電腦', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'recosc1920s2ab' },
    { name: '電腦', cls_id: ctx.classes.obj['19-s2sa'].id, slug: 'recosc1920s2sa' },
    { name: '電腦', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'recosc1920s1aa' },
    { name: '電腦', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'recosc1920s1ab' },
    { name: '電腦', cls_id: ctx.classes.obj['19-s1sa'].id, slug: 'recosc1920s1sa' },
    { name: '電腦', cls_id: ctx.classes.obj['19-j2a'].id, slug: 'recosc1920j2a' },
    { name: '電腦', cls_id: ctx.classes.obj['19-j2b'].id, slug: 'recosc1920j2b' },
    { name: '電腦', cls_id: ctx.classes.obj['19-j2c'].id, slug: 'recosc1920j2c' },
    { name: '電腦', cls_id: ctx.classes.obj['19-j2d'].id, slug: 'recosc1920j2d' },
    { name: '電腦', cls_id: ctx.classes.obj['19-j1a'].id, slug: 'recosc1920j1a' },
    { name: '電腦', cls_id: ctx.classes.obj['19-j1b'].id, slug: 'recosc1920j1b' },
    { name: '電腦', cls_id: ctx.classes.obj['19-j1c'].id, slug: 'recosc1920j1c' },
    { name: '電腦', cls_id: ctx.classes.obj['19-j1d'].id, slug: 'recosc1920j1d' },
    { name: '音樂', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'remusi1920s2aa' },
    { name: '音樂', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'remusi1920s2ab' },
    { name: '音樂', cls_id: ctx.classes.obj['19-s2sa'].id, slug: 'remusi1920s2sa' },
    { name: '音樂', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'remusi1920s1aa' },
    { name: '音樂', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'remusi1920s1ab' },
    { name: '音樂', cls_id: ctx.classes.obj['19-s1sa'].id, slug: 'remusi1920s1sa' },
    { name: '音樂', cls_id: ctx.classes.obj['19-j3a'].id, slug: 'remusi1920j3a' },
    { name: '音樂', cls_id: ctx.classes.obj['19-j3b'].id, slug: 'remusi1920j3b' },
    { name: '音樂', cls_id: ctx.classes.obj['19-j3c'].id, slug: 'remusi1920j3c' },
    { name: '音樂', cls_id: ctx.classes.obj['19-j1a'].id, slug: 'remusi1920j1a' },
    { name: '音樂', cls_id: ctx.classes.obj['19-j1b'].id, slug: 'remusi1920j1b' },
    { name: '音樂', cls_id: ctx.classes.obj['19-j1c'].id, slug: 'remusi1920j1c' },
    { name: '音樂', cls_id: ctx.classes.obj['19-j1d'].id, slug: 'remusi1920j1d' },
    { name: '音樂', cls_id: ctx.classes.obj['19-f3a'].id, slug: 'remusi1920f3a' },
    { name: '音樂', cls_id: ctx.classes.obj['19-f2a'].id, slug: 'remusi1920f2a' },
    { name: '音樂', cls_id: ctx.classes.obj['19-f1a'].id, slug: 'remusi1920f1a' },
    { name: '音樂', cls_id: ctx.classes.obj['19-j2a'].id, slug: 'remusi1920j2a' },
    { name: '音樂', cls_id: ctx.classes.obj['19-j2b'].id, slug: 'remusi1920j2b' },
    { name: '音樂', cls_id: ctx.classes.obj['19-j2c'].id, slug: 'remusi1920j2c' },
    { name: '音樂', cls_id: ctx.classes.obj['19-j2d'].id, slug: 'remusi1920j2d' },
    { name: '體育', cls_id: ctx.classes.obj['19-s3sa'].id, slug: 'rephed1920s3sa' },
    { name: '體育', cls_id: ctx.classes.obj['19-s2aa'].id, slug: 'rephed1920s2aa' },
    { name: '體育', cls_id: ctx.classes.obj['19-s1aa'].id, slug: 'rephed1920s1aa' },
    { name: '體育', cls_id: ctx.classes.obj['19-j3a'].id, slug: 'rephed1920j3a' },
    { name: '體育', cls_id: ctx.classes.obj['19-j2c'].id, slug: 'rephed1920j2c' },
    { name: '體育', cls_id: ctx.classes.obj['19-j2d'].id, slug: 'rephed1920j2d' },
    { name: '體育', cls_id: ctx.classes.obj['19-j1b'].id, slug: 'rephed1920j1b' },
    { name: '體育', cls_id: ctx.classes.obj['19-j1d'].id, slug: 'rephed1920j1d' },
    { name: '體育', cls_id: ctx.classes.obj['19-s3ab'].id, slug: 'rephed1920s3ab' },
    { name: '體育', cls_id: ctx.classes.obj['19-s2ab'].id, slug: 'rephed1920s2ab' },
    { name: '體育', cls_id: ctx.classes.obj['19-s1sa'].id, slug: 'rephed1920s1sa' },
    { name: '體育', cls_id: ctx.classes.obj['19-j3c'].id, slug: 'rephed1920j3c' },
    { name: '體育', cls_id: ctx.classes.obj['19-j2b'].id, slug: 'rephed1920j2b' },
    { name: '體育', cls_id: ctx.classes.obj['19-j1a'].id, slug: 'rephed1920j1a' },
    { name: '體育', cls_id: ctx.classes.obj['19-j1c'].id, slug: 'rephed1920j1c' },
    { name: '體育', cls_id: ctx.classes.obj['19-s3aa'].id, slug: 'rephed1920s3aa' },
    { name: '體育', cls_id: ctx.classes.obj['19-s2sa'].id, slug: 'rephed1920s2sa' },
    { name: '體育', cls_id: ctx.classes.obj['19-s1ab'].id, slug: 'rephed1920s1ab' },
    { name: '體育', cls_id: ctx.classes.obj['19-j3b'].id, slug: 'rephed1920j3b' },
    { name: '體育', cls_id: ctx.classes.obj['19-j2a'].id, slug: 'rephed1920j2a' },
    { name: '體育', cls_id: ctx.classes.obj['19-f3a'].id, slug: 'rephed1920f3a' },
    { name: '體育', cls_id: ctx.classes.obj['19-f2a'].id, slug: 'rephed1920f2a' },
    { name: '體育', cls_id: ctx.classes.obj['19-f1a'].id, slug: 'rephed1920f1a' }
  ]

  for (let coursesIndex = 0; coursesIndex < coursesData.length; ++coursesIndex) {
    courses.push(
      {
        ...coursesData[coursesIndex],
        id: uuid(),
        created_at: new Date(),
        english_name: '',
        credits: 0,
        school_dashboard_id: ctx.schoolsDashboards.obj['cdsj6 2019/2020 Dashboard'].id,
        school_id: ctx.schools.obj['school-cdsj6'].id,
        type: 'required',
        term: 0
      }
    )
  }

  // 資料庫操作
  await knex('courses').insert([
    ...courses
  ])

  // 讀取資料
  const docs = await knex.select().table('courses')

  // 返回
  ctx.courses = {
    docs,
    obj: _.keyBy(docs, (o) => {
      return o.slug
    })
  }
}
